[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bash -c 'if [ -d pref-calculator ]; then cd pref-calculator; fi; python main.py'"
healthcheckPath = ""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
